"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

def getenvvar(name, default_value=None):

    """Get environment variable or raise an error if not defined."""
    value = os.environ.get(name, default_value)
    if value is None:
        raise ImproperlyConfigured(f'Environment variable {name} is undefined')
    return value

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = getenvvar('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_celery_results",

    "binance_trader",
    "django_celery_beat",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "app.config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

STATIC_ROOT = "app.static"

WSGI_APPLICATION = "app.config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'postgres'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'postgres'),
        'HOST': os.environ.get('POSTGRES_HOST', 'db'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}

# If you have multiple apps with separate databases, add them like this:
if 'BINANCE_TRADER_DB_NAME' in os.environ:
    DATABASES['binance_trader'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': getenvvar('BINANCE_TRADER_DB_NAME'),
        'USER': getenvvar('BINANCE_TRADER_DB_USER'),
        'PASSWORD': getenvvar('BINANCE_TRADER_DB_PASSWORD'),
        'HOST': getenvvar('BINANCE_TRADER_DB_HOST'),
        'PORT': getenvvar('BINANCE_TRADER_DB_PORT'),
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ------------------------
# Celery Configuration
# ------------------------
# Broker URL (Redis) for Celery, you can adjust it with environment variables
CELERY_BROKER_URL = getenvvar('CELERY_BROKER_URL', 'redis://redis:6379/0')

# Result backend for Celery
CELERY_RESULT_BACKEND = getenvvar('CELERY_RESULT_BACKEND', 'django-db')

# Accepted content types for Celery (JSON)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Time zone configuration for Celery tasks
CELERY_TIMEZONE = TIME_ZONE  # Ensure that TIME_ZONE is defined in your settings.py
CELERY_ENABLE_UTC = True

# Maximum number of attempts to reconnect to the broker (Redis)
CELERY_BROKER_CONNECTION_MAX_RETRIES = int(getenvvar('CELERY_BROKER_CONNECTION_MAX_RETRIES', 5))

# Retry broker connection on startup
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Timeout when trying to connect to the broker (in seconds)
CELERY_BROKER_CONNECTION_TIMEOUT = int(getenvvar('CELERY_BROKER_CONNECTION_TIMEOUT', 10))

# Enable Celery Eager in development (so tasks run without a worker)
CELERY_TASK_ALWAYS_EAGER = getenvvar('CELERY_TASK_ALWAYS_EAGER', 'False').lower() in ['true', '1', 't']

# Extend results (includes more data from tasks)
CELERY_RESULT_EXTENDED = True

# Configuration for Celery Beat to use the database scheduler
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'

# Optional: Configure a timeout for hanging tasks (depends on your specific usage)
CELERY_TASK_TIME_LIMIT = int(getenvvar('CELERY_TASK_TIME_LIMIT', 300))  # Time limit in seconds

# Search paths for automatic task discovery in Django apps
CELERY_IMPORTS = ('binance_trader.tasks',)

